# Generated by Django 3.0.4 on 2020-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='datestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='filename',
            field=models.TextField(blank=True),
        ),
    ]
