# Generated by Django 3.0.4 on 2020-03-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20200313_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='datestamp',
            new_name='timestamp',
        ),
    ]
